const dashBoardWizardCount = [
    {
        id: 0,
        label: 'Active Contracts',
        count: 372,
        icon: '',
        graphType: 'line',
        graphData: [50, 59, 30, 81, 39, 90, 30],
        borderColor: '#05f0d8',
    },
    {
        id: 1,
        label: ' Billable Resource',
        count: 372,
        icon: '',
        graphType: 'line',
        graphData: [65, 59, 80, 81, 56, 55, 40],
        borderColor: '#05f044',
    },
    {
        id: 2,
        label: 'Pending Invoice',
        count: 398,
        icon: '',
        graphType: 'line',
        graphData: [30, 29, 80, 61, 39, 50, 70],
        borderColor: '#f21693',
    },
    {
        id: 3,
        label: 'Vender Applications',
        count: 232,
        icon: '',
        graphType: 'line',
        graphData: [40, 59, 10, 70, 66, 77, 40],
        borderColor: '#05f044',
    },
    // {
    //     id: 4,
    //     label: 'Work Auth Exp',
    //     count: 232,
    //     icon: '',
    //     graphType: 'line',
    //     graphData: [40, 59, 10, 70, 66, 77, 40],
    //     borderColor: '#05f044',
    // },
    // {
    //     id: 5,
    //     label: 'Ems Notes(Manual)',
    //     count: 234,
    //     icon: '',
    //     graphType: 'line',
    //     graphData: [40, 59, 10, 70, 66, 77, 40],
    //     borderColor: '#05f044',
    // },
    // {
    //     id: 6,
    //     label: 'Expired Work Auth.',
    //     count: 2712,
    //     icon: '',
    //     graphType: 'line',
    //     graphData: [40, 59, 10, 70, 66, 77, 40],
    //     borderColor: '#05f044',
    // },
    // {
    //     id: 7,
    //     label: 'Ems Activity(Auto)',
    //     count: 232,
    //     icon: '',
    //     graphType: 'line',
    //     graphData: [40, 59, 10, 70, 66, 77, 40],
    //     borderColor: '#05f044',
    // },
];

export default dashBoardWizardCount;
