export const pendingTableData = [
    {
        resourceId: 'CR540',
        contractId: 'PR-AV540',
        woRate: '40hr',
        resourceName: 'Jhonson',
        role: 'W2Employee',
        joinDate: '05/13/2023',
        status: 'submited',
        vendor: 'John',
        ssnNumber: '1234',
        phoneNumber: '9439679456',
    },
    {
        resourceId: 'CR541',
        contractId: 'PR-AV540',
        woRate: '40hr',
        resourceName: 'Jhonson',
        role: 'W2Employee',
        joinDate: '05/13/2023',
        status: 'Approved',
        vendor: 'John',
        ssnNumber: '1235',
        phoneNumber: '9439679456',
    },
    {
        resourceId: 'CR542',
        contractId: 'PR-AV540',
        woRate: '40hr',
        resourceName: 'Jhonson',
        role: 'W2Employee',
        joinDate: '05/13/2023',
        status: 'Pending',
        vendor: 'John',
        ssnNumber: '1735',
        phoneNumber: '9439679456',
    },
    {
        resourceId: 'CR543',
        contractId: 'PR-AV540',
        woRate: '40hr',
        resourceName: 'Jhonson',
        role: 'W2Employee',
        joinDate: '05/13/2023',
        status: 'Approved',
        vendor: 'John',
        ssnNumber: '1735',
        phoneNumber: '9439679456',
    },
    {
        resourceId: 'CR544',
        contractId: 'PR-AV540',
        woRate: '40hr',
        resourceName: 'Jhonson',
        role: 'W2Employee',
        joinDate: '05/13/2023',
        status: 'Pending',
        vendor: 'John',
        ssnNumber: '1735',
        phoneNumber: '9439679456',
    },
    // {
    //     resourceId: 'CR545',
    //     contractId: 'PR-AV540',
    //     woRate: '40hr',
    //     resourceName: 'Jhonson',
    //     role: 'W2Employee',
    //     joinDate: '05/13/2023',
    //     status: 'submited',
    //     vendor: 'John',
    //     ssnNumber: '1735',
    //     phoneNumber: '9439679456',
    // },
    // {
    //     resourceId: 'CR546',
    //     contractId: 'PR-AV540',
    //     woRate: '40hr',
    //     resourceName: 'Jhonson',
    //     role: 'W2Employee',
    //     joinDate: '05/13/2023',
    //     status: 'submited',
    //     vendor: 'John',
    //     ssnNumber: '1735',
    //     phoneNumber: '9439679456',
    // },
    // {
    //     resourceId: 'CR547',
    //     contractId: 'PR-AV540',
    //     woRate: '40hr',
    //     resourceName: 'Jhonson',
    //     role: 'W2Employee',
    //     joinDate: '05/13/2023',
    //     status: 'submited',
    //     vendor: 'John',
    //     ssnNumber: '1735',
    //     phoneNumber: '9439679456',
    // },
    // {
    //     resourceId: 'CR548',
    //     contractId: 'PR-AV540',
    //     woRate: '40hr',
    //     resourceName: 'Jhonson',
    //     role: 'W2Employee',
    //     joinDate: '05/13/2023',
    //     status: 'submited',
    //     vendor: 'John',
    //     ssnNumber: '1735',
    //     phoneNumber: '9439679456',
    // },
    // {
    //     resourceId: 'CR549',
    //     contractId: 'PR-AV540',
    //     woRate: '40hr',
    //     resourceName: 'Jhonson',
    //     role: 'W2Employee',
    //     joinDate: '05/13/2023',
    //     status: 'submited',
    //     vendor: 'John',
    //     ssnNumber: '1735',
    //     phoneNumber: '9439679456',
    // },
];
