export const userData = [
    {
        id: '1',
        user: 'Austin Ray',
        role: 'Admin',
        email: 'austinray@gmail.com',
        phone: '2010004255',
        verified: 'Mar 01,2023',
        status: 'Active',
        verifiedBy: 'phone',
    },
    {
        id: '2',
        user: 'Asiya Javayant',
        role: 'Admin',
        email: 'austinray@gmail.com',
        phone: '2010004255',
        verified: 'Mar 01,2023',
        status: 'Pending',
        verifiedBy: 'email',
    },
    {
        id: '3',
        user: 'Ivan Magalhaes',
        role: 'Admin',
        email: 'austinray@gmail.com',
        phone: '2010004255',
        verified: 'Mar 01,2023',
        status: 'Active',
        verifiedBy: 'email',
    },
    {
        id: '4',
        user: 'Onyama Limba',
        role: 'Admin',
        email: 'austinray@gmail.com',
        phone: '2010004255',
        verified: 'Mar 01,2023',
        status: 'Suspend',
        verifiedBy: 'phone',
    },
];
