export const earningsDecuctionData = [
    {
        category:"Earnings",
        name:'Overtime',
        description:'Additional pay for extra hours worked',
        type:'Variable',
        rate:'---',
        frequency:"Hourly",
        startDate:"---",
        endDate:"---",
        amount:"---",
    },
    {
        category:"Earnings",
        name:'Bonuses',
        description:'Special bonuse',
        type:'Variable',
        rate:'---',
        frequency:"Yearly",
        startDate:"---",
        endDate:"---",
        amount:"---",
    },
    {
        category:"Deductions",
        name:'Health Insurance',
        description:'Premiums for health coverage',
        type:'Fixed',
        rate:'---',
        frequency:"Monthly",
        startDate:"---",
        endDate:"---",
        amount:"---",
    },
    {
        category:"Deductions",
        name:'Loan Payments',
        description:'Payment for any loans',
        type:'Fixed',
        rate:'---',
        frequency:"Monthly",
        startDate:"---",
        endDate:"---",
        amount:"---",
    },
    {
        category:"Deductions",
        name:'Advance Payments',
        description:'Payment for any advance',
        type:'Fixed',
        rate:'---',
        frequency:"Monthly",
        startDate:"---",
        endDate:"---",
        amount:"---",
    },
  
   
    
]